
project_id = "tvxhruyqhtqeacscpyzk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions]
[functions.verify-waste-image]
verify_jwt = true
