// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvxhruyqhtqeacscpyzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2eGhydXlxaHRxZWFjc2NweXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzA5MTksImV4cCI6MjA2MDQ0NjkxOX0.o4F8KbThtju7x82jG-JFFdMddZmHFpIdga2tQPVTjVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);